# -*- coding: utf-8 -*-
"""Mad-Libs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zz6HZMIjWx7AJBYRXCvFrnqGzjzSFNnP
"""

print ("Hello World")

#Mad Libs game
name  =  input("Enter your name:")
place =  input("Enter your place:")
animal= input("Enter your animal")
exclamation=input("Enter your exclamation:")
verb=input ("Enter your verb:")
noun=input("Enter your noun:")
#Mad Libs story paragraph
story = f"""
one day, {name} went to {place} and saw a {animal} running around. "{exclamation}!" {name} exclaimed.
without hesitation, {name} decided to {verb} after the {animal}.
After a while, they both stumbled upon a mysterious {noun}. It was an unforgettable adventure!
"""
print("Your story is:")
print(story)